name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: getdue-dev/.github/.github/workflows/lint.yml@main
    secrets: inherit
